backupIntervalSeconds: 1800
backupDeletionThresholdSeconds: 86400
lastInteractionThresholdSeconds: 600
compressionLevel: 9
broadcastMessages: true
skipBackupMessage: Skipped backup due to no player activity.
backupStartedMessage: Started backup...
backupSucceededMessage: Backup complete.
backupFailedMessage: Backup failed. Check the server logs for more details.
fileSkipRegexes:
  - '\.jar$'
  - '\.zip$'
directorySkipRegexes:
  - 'logs'
  - 'cache'
  - 'libraries'

